name: semeval2026
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyarrow
  - python-dotenv
  - jupyter
  - ipykernel
  - scipy
  - pip:
      - kaggle
      - xgboost
      - tree-sitter
      - tree-sitter-python
      - tree-sitter-java
      - tree-sitter-cpp
